'use client';
/* eslint-disable @next/next/no-img-element -- Private images use authenticated Core endpoints. */
import { useState } from 'react';
import { blankBoxClient } from '@/lib/blank-box-client';
import { prepareCover } from '@/lib/artwork';
import type { MediaItem } from '@/lib/media';

export function ArtworkGalleryEditor({initialReleaseId='',focused=false,item,busy,beforeChange,onWorkingChange,onChanged}:{initialReleaseId?:string;focused?:boolean;item:MediaItem;busy:boolean;beforeChange:()=>boolean;onWorkingChange?:(working:boolean)=>void;onChanged:(item:MediaItem)=>void}) {
  const[releaseId,setReleaseId]=useState(initialReleaseId);const[role,setRole]=useState('front');const[label,setLabel]=useState('');const[working,setWorking]=useState(false);const[error,setError]=useState('');
  const editions=[...new Map(item.sources.filter(source=>source.type==='physical'&&source.physicalReleaseId).map(source=>[source.physicalReleaseId!,source])).values()];
  const perform=async(action:()=>Promise<MediaItem>)=>{if(!beforeChange())return;setWorking(true);onWorkingChange?.(true);setError('');try{onChanged(await action());}catch(error){setError((error as Error).message);}finally{setWorking(false);onWorkingChange?.(false);}};
  const upload=async(files:FileList|null)=>{if(!files?.length||!beforeChange())return;setWorking(true);onWorkingChange?.(true);setError('');let latest:MediaItem|null=null;try{for(const file of Array.from(files)){latest=await blankBoxClient.uploadGalleryArtwork(item.id,await prepareCover(file),{releaseId,label:label||file.name.slice(0,120),role});}}catch(error){setError((error as Error).message);}finally{if(latest)onChanged(latest);setWorking(false);onWorkingChange?.(false);}};
  return <section className={`catalog-gallery kind-${item.kind}`}><h3>Saved artwork</h3><p>Keep front, back, spine and other artwork with a physical edition or the title. Choose one image as the main Blank Box cover.</p>
    <div className="form-grid"><label className="field"><span>Attach to</span><select value={releaseId} onChange={event=>setReleaseId(event.target.value)}><option value="">This title</option>{editions.map(source=><option key={source.physicalReleaseId} value={source.physicalReleaseId}>{[source.label,source.edition,source.packaging,source.releaseLabel].filter(Boolean).join(' · ')}</option>)}</select></label><label className="field"><span>Image role</span><select value={role} onChange={event=>setRole(event.target.value)}>{['front','back','spine','disc','other'].map(value=><option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select></label><label className="field"><span>Image label <small>optional</small></span><input value={label} maxLength={120} onChange={event=>setLabel(event.target.value)}/></label></div>
    <label className="subtle-button">Add artwork<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy||working} onChange={event=>{void upload(event.target.files);event.target.value='';}}/></label><small>Up to 12 images per edition and 48 per title. Each image is saved as a small private JPEG.</small>
    <div className="artwork-gallery-grid">{(item.artworkGallery||[]).filter(image=>!focused||(image.releaseId||'')===releaseId).map(image=><figure key={image.id}><a href={image.url} target="_blank" rel="noopener noreferrer"><img src={image.url} alt={image.label} loading="lazy"/></a><figcaption>{image.label} · {image.role}{image.releaseId&&<small>{editions.find(source=>source.physicalReleaseId===image.releaseId)?.edition||'Physical edition'}</small>}{image.primary&&<strong>Main cover</strong>}</figcaption><button type="button" className="text-button" disabled={busy||working||image.primary} onClick={()=>void perform(async()=>{const result=await blankBoxClient.action('gallery-primary',{id:item.id,artworkId:image.id});return result.item!;})}>Use as main cover</button><button type="button" className="text-button" disabled={busy||working} onClick={()=>{if(window.confirm(`Remove ${image.label} from saved artwork?`))void perform(async()=>{const result=await blankBoxClient.action('gallery-remove',{id:item.id,artworkId:image.id,confirm:true});return result.item!;});}}>Remove image</button></figure>)}</div>{error&&<p role="alert" className="error-text">{error}</p>}
  </section>;
}

export function ArtworkGalleryView({item}:{item:MediaItem}) {
  if(!item.artworkGallery?.length)return null;
  return <section className={`detail-artwork-gallery kind-${item.kind}`}><h4>Your artwork</h4><div className="artwork-gallery-grid">{item.artworkGallery.map(image=><figure key={image.id}><a href={image.url} target="_blank" rel="noopener noreferrer"><img src={image.url} alt={image.label} loading="lazy"/></a><figcaption>{image.label} · {image.role}{image.releaseId&&<small>{item.sources.find(source=>source.physicalReleaseId===image.releaseId)?.edition||'Physical edition'}</small>}</figcaption></figure>)}</div></section>;
}
